CREATE TABLE MEMBER_TBL(
    MEMBER_ID VARCHAR2(20),
    MEMBER_PWD VARCHAR2(30),
    MEMBER_NAME VARCHAR2(20),
    MEMBER_GENDER VARCHAR2(3),
    MEMBER_AGE NUMBER,
    MEMBER_EMAIL VARCHAR2(30),
    MEMBER_PHONE VARCHAR2(11),
    MEMBER_ADDRESS VARCHAR2(100),
    MEMBER_HOBBY VARCHAR2(50),
    MEMBER_DATE TIMESTAMP DEFAULT SYSTIMESTAMP
);

-- MEMBER_ID에 PRIMARY KEY 제약조건 추가
ALTER TABLE MEMBER_TBL
ADD CONSTRAINT MEMBER_PK PRIMARY KEY(MEMBER_ID);

-- MEMBER_PWD에 NOT NULL 제약조건 추가
ALTER TABLE MEMBER_TBL
MODIFY MEMBER_PWD NOT NULL;

-- MEMBER_NAME에 NOT NULL 제약조건 추가
ALTER TABLE MEMBER_TBL
MODIFY MEMBER_NAME NOT NULL;

-- MEMBER_GENDER에 CHECK('남',여') 제약조건 추가
ALTER TABLE MEMBER_TBL
ADD CHECK(MEMBER_GENDER IN('남','여'));

INSERT INTO MEMBER_TBL 
VALUES('admin', 'admin', '관리자', '남', 33, 'admin@iei.or.kr', 
'01023456789', '서울시 종로구', '수영,골프', DEFAULT);

--DELETE FROM MEMBER_TBL;

SELECT * FROM MEMBER_TBL;
